### ISSUE TITLE
Talk explicitly about |?

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p3-regex-basics#1]
### Canvas Link

https://learning.flatironschool.com/courses/6049/pages/regex-basics?module_item_id=468001

### Concern

I solved the regex lab using the "|" operator

`my_pattern = r"It's such a lovely day today.|Some weather we're having today, huh\?|Maybe today's just not my day."`

which is pretty ugly, but I wasn't sure how else to solve this given that the tests were looking for a fullmatch for each string. If this was the intended way to solve this lab, we might want to explicitly tell students about the or operator -  "|" - in this reading. We give an example of the "|" that could let students infer what it does (this is how I figured out how to use it, after looking it up and verifying that it was doing what I thought it was doing), but we don't actually tell them how it works. If our intention is to force students to look this up on their own, this is fine. If that's not our goal, we should probably talk about that in this reading (especially since this will be students' first introduction to regex).

We can also let them know that there's a 'quick reference' they can use in regex 101 to look up different regular expression patterns.

**Comment by professor-ben** [comment]
The extensible solution to this was horrendous, but I figure that's kind of the point with regular expressions (that's why I went with 1, then 2, then more sentences. To make it more horrendous). I'll make the resources a little more explicit here and provide some more hints. I'll add in a blurb on the "|" operator as well.
