### ISSUE TITLE
Possible Typos

### ISSUE THREAD

**Issue by foreverluiscastro** [learn-co-curriculum/python-p3-regex-basics#2]
### Canvas Link

https://learning.flatironschool.com/courses/6049/pages/regex-basics?module_item_id=468001

### Concern

In the chapter Only specific characters, in the last sentence, the lesson mentions Rubular. I think this may be left over from the ruby course?

Then in the chapter Example:Double Vowels, Rubular is mentioned again in the first sentence.

Since ruby will not be covered in the curriculum anymore it may be confusing for new students when they get to this part.

**Comment by professor-ben** [comment]
Almost certainly! Will update. Thank you.
